name: todo_share
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_mobile_ads: ^5.1.0
  google_fonts: ^6.2.0
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  firebase_core: ^2.32.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  sign_button: ^2.0.6
  firebase_storage: ^11.7.7
  uuid: ^4.4.0
  intl: ^0.18.1
  flutter_localization: ^0.2.0
  table_calendar: ^3.0.9
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/